name: Rosy Photo Booth CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint --max-warnings 0

      - name: Build
        run: npm run build
